# Generated by Django 4.0.2 on 2022-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(default='Headline', max_length=200),
        ),
    ]
