# Generated by Django 4.0.2 on 2022-04-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(max_length=200),
        ),
    ]
